// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/consulta-agente.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var consulta_agente_default = defineTool({
  name: "consulta_agente",
  title: "Consultar agente",
  description: "Consulta p\xFAblica de dados de um agente do DMEN Gestor. Requer n\xFAmero de agente, n\xFAmero do BI e a chave \xFAnica fornecida pelo sistema.",
  inputSchema: {
    numero_agente: z.string().min(1).describe("N\xFAmero de agente"),
    bi: z.string().min(1).describe("N\xFAmero do Bilhete de Identidade"),
    chave_unica: z.string().min(1).describe("Chave \xFAnica de 12 caracteres fornecida pelo sistema")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ numero_agente, bi, chave_unica }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Configura\xE7\xE3o do backend indispon\xEDvel." }], isError: true };
    }
    const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const { data, error } = await supabase.rpc("consulta_publica_agente", {
      _numero_agente: numero_agente.trim(),
      _bi: bi.trim(),
      _chave: chave_unica.trim()
    });
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    const row = Array.isArray(data) ? data[0] : data;
    if (!row) {
      return { content: [{ type: "text", text: "Nenhum agente encontrado com os dados fornecidos." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(row, null, 2) }],
      structuredContent: { agente: row }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dmen-gestor-mcp",
  title: "DMEN Gestor MCP",
  version: "0.1.0",
  instructions: "Ferramentas do DMEN Gestor (Educa\xE7\xE3o \u2014 Namacunde). Use `consulta_agente` para consultar publicamente os dados de um agente fornecendo o n\xFAmero de agente, BI e chave \xFAnica.",
  tools: [consulta_agente_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
