-- Adicionar novos campos na tabela professores baseado no documento HTML
ALTER TABLE public.professores 
  ADD COLUMN IF NOT EXISTS numero_cadastro text,
  ADD COLUMN IF NOT EXISTS numero_agente text,
  ADD COLUMN IF NOT EXISTS idade integer,
  ADD COLUMN IF NOT EXISTS genero text,
  ADD COLUMN IF NOT EXISTS arquivo_pessoal text,
  ADD COLUMN IF NOT EXISTS funcao text,
  ADD COLUMN IF NOT EXISTS categoria text,
  ADD COLUMN IF NOT EXISTS nivel_academico text,
  ADD COLUMN IF NOT EXISTS formado_em text,
  ADD COLUMN IF NOT EXISTS regime_contrato text,
  ADD COLUMN IF NOT EXISTS inicio_funcao date,
  ADD COLUMN IF NOT EXISTS tempo_servico text,
  ADD COLUMN IF NOT EXISTS qtd_processo_disciplinar integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estado_civil text,
  ADD COLUMN IF NOT EXISTS data_nascimento date,
  ADD COLUMN IF NOT EXISTS provincia text,
  ADD COLUMN IF NOT EXISTS comuna text,
  ADD COLUMN IF NOT EXISTS bairro_localidade text,
  ADD COLUMN IF NOT EXISTS condicao_fisica text,
  ADD COLUMN IF NOT EXISTS estado_saude text,
  ADD COLUMN IF NOT EXISTS actividade text DEFAULT 'activo',
  ADD COLUMN IF NOT EXISTS agente_transferido boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS dependentes text,
  ADD COLUMN IF NOT EXISTS num_dependentes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nome_parceira text,
  ADD COLUMN IF NOT EXISTS telefone_parceira text,
  ADD COLUMN IF NOT EXISTS outro_familiar text;